711 remove num chunks from public input
scroll-tech/zkevm-circuits pull request #712
Opened 2023-08-02 16:44 UTC by zhenfeizhang

### Description

[_PR description_]

### Issue Link

[_link issue here_]

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Contents

- [_item_]

### Rationale

[_design decisions and extended information_]

### How Has This Been Tested?

[_explanation_]

<hr>

## How to fill a PR description 

Please give a concise description of your PR.

The target readers could be future developers, reviewers, and auditors. By reading your description, they should easily understand the changes proposed in this pull request.

MUST: Reference the issue to resolve

### Single responsability

Is RECOMMENDED to create single responsibility commits, but not mandatory.

Anyway, you MUST enumerate the changes in a unitary way, e.g.

```
This PR contains:
- Cleanup of xxxx, yyyy
- Changed xxxx to yyyy in order to bla bla
- Added xxxx function to ...
- Refactored ....
```

### Design choices

RECOMMENDED to:
- What types of design choices did you face?
- What decisions you have made?
- Any valuable information that could help reviewers to think critically

2023-08-03 07:20 UTC, silathdiir commented
Hi @zhenfeizhang, @kunxian-xia and @lispc, this PR could pass aggregation-tests with scroll-prover PR https://github.com/scroll-tech/scroll-prover/pull/194.

2023-08-03 13:15 UTC, kunxian-xia commented
@zhenfeizhang The pr #686 is still buggy. And can you change the base branch of these sub-PRs to this branch? This will make sure that all changes in the sub-PRs are included in this PR.

2023-08-03 14:20 UTC, zhenfeizhang commented
> @zhenfeizhang The pr #686 is still buggy. And can you change the base branch of these sub-PRs to this branch? This will make sure that all changes in the sub-PRs are included in this PR.

Oh missed that comment. will address

2023-08-04 13:23 UTC, kunxian-xia requested changes

2023-08-04 13:23 UTC, kunxian-xia commented on aggregator/README.md
We need to update the paragraphs which are related to how the padding chunk proof is generated. For example, we no longer need the **empty chunk** as the padding chunk proof is **not** the chunk proof for empty chunk.

2023-08-04 13:23 UTC, kunxian-xia commented on aggregator/README.md
>  7. chunk[i]'s data_hash len is `0` when chunk[i] is padded
This is out-dated (and wrong) requirement (7).

2023-08-04 13:23 UTC, kunxian-xia commented on aggregator/src/core.rs
>      // 6. chunk[i]'s prev_state_root == post_state_root when chunk[i] is padded
These two requirements (6 & 7) no longer hold (i.e. the comments need to be updated).

2023-08-04 13:23 UTC, kunxian-xia commented on aggregator/src/core.rs
>  // 7. chunk[i]'s data_hash == "" when chunk[i] is padded
The constraints (6 & 7) are no longer hold for padding chunk (i.e. the comments need to be updated).

2023-08-04 13:23 UTC, kunxian-xia commented on aggregator/src/core.rs
> +                // that means the data_hash length is 32 * number_of_valid_snarks
The comment here is **not** accurate, as `chunk[i].data_hash = last_real_chunk.data_hash` when chunk[i] is padded. The preimage of batch's data hash does not include padded chunk's data hash. Therefore the batch data hash input len **must** equal to `32 * number_of_valid_snarks`.

2023-08-04 13:23 UTC, kunxian-xia commented on aggregator/src/core.rs
> +                //
It will help anyone who is interested in the code if we can leave some comments here to explain that 
- if the num_of_valid_snarks <= 4, which only needs 1 `keccak-f` round. Therefore the batch's data hash (input, len, data_rlc, output_rlc) are in the first 300 keccak rows;
- else if the num_of_valid_snarks <= 8, which needs 2 `keccak-f` rounds. Therefore the batch's data hash (input, len, data_rlc, output_rlc) are in the 2nd 300 keccak rows;
- else the num_of_valid_snarks <= 12, which needs 3 `keccak-f` rounds. Therefore the batch's data hash (input, len, data_rlc, output_rlc) are in the 3rd 300 keccak rows;

2023-08-04 13:23 UTC, kunxian-xia commented on aggregator/src/core.rs
>      }
Consider one corner case: 
>  [chunk0, chunk1, chunk2, chunk3, chunk3, chunk3, ..., chunk3] where chunk1 and chunk2 are empty chunk (i.e. their data hash = keccak("")).

Then the the `chunk_are_valid` that computed by the circuit would be `[true, true, false, true, false, false, ..., false]`. That is, only 3 out of 10 booleans are true which is not the case. Then honest prover will fail to produce a proof. 

To solve this, I think we can just use the following codes:
```rust
let is_padding = rlc_config.load_private(region, chunk_is_padding[i], offset)?;
rlc_config.conditional_enforce_equal(
    region, 
    chunk_pi_hash_rlc_cells[i-1], 
    chunk_pi_hash_rlc_cells[i], 
    offset,
)?;
```

2023-08-04 13:28 UTC, kunxian-xia commented
Only the last comment is potential vulnerability while the others are primarily related to docs.

2023-08-04 14:12 UTC, zhenfeizhang commented on aggregator/src/core.rs
>      }
I think your design is nicer. Will change.

Though FWIW, 
```
// chunk[i].piHash =
//     keccak(
//        &chain id ||
//        chunk[i].prevStateRoot ||
//        chunk[i].postStateRoot ||
//        chunk[i].withdrawRoot  ||
//        chunk[i].datahash)
```
iiuc chunk1 and chunk 2's data hash will be different even though they are both empty chunks.
The `block #`, `time stamps` etc will also get hashed into `datahash`

2023-08-04 14:19 UTC, kunxian-xia commented on aggregator/src/core.rs
>      }
You're right, data_hash should be different even for empty chunks.

2023-08-04 14:45 UTC, zhenfeizhang commented on aggregator/README.md
>  7. chunk[i]'s data_hash len is `0` when chunk[i] is padded
fixed with 246b4715aad1d798943b8d9931b854d48c775e14

2023-08-04 14:45 UTC, zhenfeizhang commented on aggregator/src/core.rs
>      // 6. chunk[i]'s prev_state_root == post_state_root when chunk[i] is padded
fixed with 246b4715aad1d798943b8d9931b854d48c775e14

2023-08-04 14:45 UTC, zhenfeizhang commented on aggregator/src/core.rs
>  // 7. chunk[i]'s data_hash == "" when chunk[i] is padded
fixed with 246b4715aad1d798943b8d9931b854d48c775e14

2023-08-04 14:45 UTC, zhenfeizhang commented on aggregator/src/core.rs
> +                // that means the data_hash length is 32 * number_of_valid_snarks
fixed with 246b4715aad1d798943b8d9931b854d48c775e14

2023-08-04 14:45 UTC, zhenfeizhang commented on aggregator/src/core.rs
> +                //
fixed with 246b4715aad1d798943b8d9931b854d48c775e14

2023-08-04 15:22 UTC, kunxian-xia reviewed
One last problem is that `is_final` cells are not exported and not enforced to be true.

2023-08-04 15:37 UTC, zhenfeizhang commented
> One last problem is that `is_final` cells are not exported and not enforced to be true.

fixed in 24014494305999b1f5c74fc4743e5ffb2aa20da0

2023-08-04 17:37 UTC, kunxian-xia approved these changes

2023-08-04 17:57 UTC, merged

2023-08-04 17:57 UTC, icemelon commented on aggregator/README.md
> +for i in 1 ... __k-1__
move this line inside the code block.

2023-08-04 17:57 UTC, icemelon commented on aggregator/figures/architecture.jpg
update the "batch" bracket to only include up to all valid chunks.

2023-08-04 17:57 UTC, icemelon commented on aggregator/src/aggregation/rlc/gates.rs
> +            || "const one hundred and thirty six",
```suggestion
            || "const 136",
```

2023-08-04 17:57 UTC, icemelon commented on aggregator/src/aggregation/rlc/gates.rs
> +            || "const two to thirty two",
```suggestion
            || "const 2^32",
```